apiVersion: v1
kind: Service
metadata:
  name: admin-server
  labels:
    app: admin-server
spec:
  selector:
    app: admin-server
  ports:
    - protocol: TCP
      port: 9090       # Or the port your admin-server uses
      targetPort: 9090  # Or the port your admin-server uses
      nodePort: 30008
  type: NodePort
