apiVersion: v1
kind: Service
metadata:
  name: genai-service
  labels:
    app: genai-service
spec:
  selector:
    app: genai-service
  ports:
    - protocol: TCP
      port: 8084       #  Or the port your genai-service uses
      targetPort: 8084  #  Or the port your genai-service uses
      nodePort: 30004
  type: NodePort
