apiVersion: v1
kind: Service
metadata:
  name: vets-service
  labels:
    app: vets-service
spec:
  selector:
    app: vets-service
  ports:
    - protocol: TCP
      port: 8083       #  Or the port your vets-service uses
      targetPort: 8083  #  Or the port your vets-service uses
      nodePort: 30002
  type: NodePort
