apiVersion: v1
kind: Service
metadata:
  name: visits-service
  labels:
    app: visits-service
spec:
  selector:
    app: visits-service
  ports:
    - protocol: TCP
      port: 8082       #  Or the port your visits-service uses
      targetPort: 8082  #  Or the port your visits-service uses
      nodePort: 30003
  type: NodePort
