apiVersion: v1
kind: Service
metadata:
  name: zipkin-server
  labels:
    app: zipkin-server
spec:
  selector:
    app: zipkin-server
  ports:
    - protocol: TCP
      port: 9411
      targetPort: 9411
      nodePort: 30009
  type: NodePort
